<a href="https://colab.research.google.com/github/refianP13/Data-Analyst/blob/main/Copy_of_%5BMENTOR_VER%5D_SESI_6_%26_7_Variable%2C_Tipe_Data%2C_dan_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numeric: Integer & Float
Pengenalan tipe data numerik

In [ ]:
x = 25

In [ ]:
print(x)

25

In [ ]:
print(x + 5)

30

In [ ]:
type

type

In [ ]:
a = 3.5

In [ ]:
print(a)

3.5

In [ ]:
type(a)

float

# Mathematical Process

In [ ]:
# penjumlahan
#    25  3.5
print(x + a)

28.5

In [ ]:
# pengurangan
print(x - a)

21.5

In [ ]:
# perkalian
print(x * a)

87.5

In [ ]:
# pembagian
print(x / a)

7.142857142857143

In [ ]:
# pembagian (pembulatan)
print(x // a)

7.0

In [ ]:
# pangkat
#    25 ^  3.5
print(x ** a)

78125.0

In [ ]:
# pangkat
print(x ** 2)

625

In [ ]:
# akar 2
print(x ** (1/2))

5.0

In [ ]:
print(x ** 0.5)

5.0

In [ ]:
import math
math.ceil(7/4)

2

In [ ]:
math.floor(7/4)

1

In [ ]:
print(7/4)

1.75

In [ ]:
round(7/4)

2

In [ ]:
# modulo / modulus / sisa pembagian
print(25 % 2)

1

# Boolean

In [ ]:
type(True)

bool

In [ ]:
type(False)

bool

In [ ]:
True + True

2

In [ ]:
True + False

1

In [ ]:
True and True

True

In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
False or False

False

# Operasi Perbandingan

In [ ]:
# > lebih dari
# < kurang dari
# >= lebih dari atau sama dengan
# <= kurang dari atau sama dengan
# == sama dengan
# != tidak sama dengan
# operasi perbandingan akan menghasilkan True atau False

In [ ]:
a = 4
b = 5

In [ ]:
hasil = a > b

In [ ]:
print(hasil)

False

In [ ]:
a == b

False

In [ ]:
a < b

True

# String

In [ ]:
message = "Hi, my name is Ridho"
print(message)

Hi, my name is Ridho

In [ ]:
type(message)

str

In [ ]:
message2 = 'Hi, my name is Ridho'
print(message2)

Hi, my name is Ridho

In [ ]:
type(message2)

str

In [ ]:
contoh_txt = "I'm Ridho"
print(contoh_txt)

I'm Ridho

In [ ]:
type(contoh_txt)

str

In [ ]:
contoh_txt2 = 'I'm Ridho'
print(contoh_txt2)

SyntaxError: unterminated string literal (detected at line 1) (ipython-input-2249241826.py, line 1)

In [ ]:
contoh_txt3 = 'I\'m Ridho'
print(contoh_txt3)

I'm Ridho

In [ ]:
contoh_txt4 = 'Hi, my name is Ridho "The Data Scientist"'
print(contoh_txt4)

Hi, my name is Ridho "The Data Scientist"

In [ ]:
contoh_txt5 = '''Hi, my name is Ridho
I'm a Data Scientist'''
print(contoh_txt5)

Hi, my name is Ridho
I'm a Data Scientist

In [ ]:
contoh_txt6 = "Hi, my name is Ridho
I am a Data Scientist"
print(contoh_txt6)

SyntaxError: unterminated string literal (detected at line 1) (ipython-input-3635559089.py, line 1)

In [ ]:
contoh_txt7 = "Hi, my name is Ridho\
I am a Data Scientist"
print(contoh_txt7)

Hi, my name is RidhoI am a Data Scientist

## add new string

In [ ]:
sentence1 = "Last week I went to Bangkok."
sentence2 = "I liked to shop there."

In [ ]:
combine1 = sentence1 + sentence2
print(combine1)

Last week I went to Bangkok.I liked to shop there.

In [ ]:
combine2 = sentence1 + " " + sentence2
print(combine2)

Last week I went to Bangkok. I liked to shop there.

In [ ]:
contoh_txt = 'im"ridho'
print(contoh_txt)

im"ridho

In [ ]:
sentence3 = "I went to Bangkok using airplane."
combine3 = combine2 + " " + sentence3
print(combine3)

Last week I went to Bangkok. I liked to shop there. I went to Bangkok using airplane.

In [ ]:
sentence3 = "I went to Bangkok using airplane."
combine3 = combine2 + "\n" + sentence3
print(combine3)

Last week I went to Bangkok. I liked to shop there.
I went to Bangkok using airplane.

In [ ]:
combine4 = f"{sentence1} {sentence2} {sentence3} \n The tickets cost me IDR {900000*3}"
print(combine4)

Last week I went to Bangkok. I liked to shop there. I went to Bangkok using airplane.
 The tickets cost me IDR 2700000

# String Methods

In [ ]:
kalimat = "Saya suka bepergian dengan keluarga"

In [ ]:
kalimat.upper()

'SAYA SUKA BEPERGIAN DENGAN KELUARGA'

In [ ]:
print(kalimat)

Saya suka bepergian dengan keluarga

In [ ]:
kalimat = kalimat.upper()
print(kalimat)

SAYA SUKA BEPERGIAN DENGAN KELUARGA

In [ ]:
print(kalimat.upper())

SAYA SUKA BEPERGIAN DENGAN KELUARGA

In [ ]:
kalimat.lower()

'saya suka bepergian dengan keluarga'

In [ ]:
kalimat.swapcase()

'sAYA SUKA BEPERGIAN DENGAN KELUARGA'

In [ ]:
4 + 2

6

In [ ]:
kalimat.title()

'Saya Suka Bepergian Dengan Keluarga'

In [ ]:
kalimat.isalpha()

False

In [ ]:
kalimat.isalnum()

False

In [ ]:
"sayasukabepergiandengankeluarga".isalpha()

True

In [ ]:
"ridho123".isalnum()

True

In [ ]:
kalimat.count("s")

1

In [ ]:
kalimat.replace('a', 'i')

'Siyi suki bepergiin dengin keluirgi'

In [ ]:
kalimat.replace("keluarga", "teman")

'Saya suka bepergian dengan teman'

## String Indexing

In [ ]:
kalimat[0]

'S'

In [ ]:
# cara pertama
kalimat[15]

'g'

In [ ]:
# cara kedua
kalimat[kalimat.index('g')]

'g'

In [ ]:
kalimat.index('a')

1

In [ ]:
kalimat[0:3]

'Say'

In [ ]:
kalimat.split()

['Saya', 'suka', 'bepergian', 'dengan', 'keluarga']

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# contoh bikin kolom baru
df["name"] = "Ridho Aryo"
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,name
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,Ridho Aryo
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,Ridho Aryo
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,Ridho Aryo
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,Ridho Aryo
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,Ridho Aryo
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,Ridho Aryo
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,Ridho Aryo
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,Ridho Aryo
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,Ridho Aryo
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,Ridho Aryo

In [ ]:
name = df['name']
name

0        Ridho Aryo
1        Ridho Aryo
2        Ridho Aryo
3        Ridho Aryo
4        Ridho Aryo
            ...
16995    Ridho Aryo
16996    Ridho Aryo
16997    Ridho Aryo
16998    Ridho Aryo
16999    Ridho Aryo
Name: name, Length: 17000, dtype: object

In [ ]:
df['First_Name'] = df['name'].str[0:5]
df['Last_Name'] = df['name'].str[6:10]
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,name,First_Name,Last_Name
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,Ridho Aryo,Ridho,Aryo
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,Ridho Aryo,Ridho,Aryo
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,Ridho Aryo,Ridho,Aryo
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,Ridho Aryo,Ridho,Aryo
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,Ridho Aryo,Ridho,Aryo