<a href="https://colab.research.google.com/github/refianP13/Data-Analyst/blob/main/Copy_of_DQLab_Intro_to_Database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Latar Belakang**


<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20Main%20Problem.png" width="100%">

Dalam bisnis restoran, data transaksi penjualan merupakan sumber informasi penting yang dapat digunakan untuk mengevaluasi kinerja bisnis dan mendukung pengambilan keputusan. Manajemen membutuhkan laporan yang mampu memberikan gambaran mengenai pendapatan, produk terlaris, pola pembelian pelanggan, serta tren penjualan yang terjadi.

SQL digunakan untuk mengolah dan menganalisis data transaksi agar menghasilkan informasi yang relevan dan mudah dipahami oleh manajemen. Melalui dataset Pizza Transaction, analisis dilakukan untuk mengidentifikasi performa penjualan, mengetahui produk yang paling diminati, serta menemukan peluang peningkatan bisnis berdasarkan data yang tersedia.

<img src="https://i.pinimg.com/originals/3f/16/66/3f1666fa70ae1e30b0b5b4c862c363aa.gif" width="30%">
<br>

Manajemen memintamu untuk memberikan data yang mereka butuhkan baik mengenai detail transaksi ataupun summary dari datanya. Sebagai Data Engineer, tujuanmu saat ini adalah untuk memprovide kebutuhan tersebut.

<img src="https://cdn.dribbble.com/userupload/21955253/file/original-cbc2133f09318197a07643d9033a3f16.gif" width="50%">

Untuk memenuhi kebutuhan tersebut, kamu akan melakukan proses ekstraksi dan pengolahan data dari **database** transaksi pizza menggunakan SQL. Data yang dihasilkan harus akurat, konsisten, dan mudah digunakan oleh tim bisnis maupun Data Analyst dalam proses analisis lebih lanjut. Hasil pengolahan data ini nantinya akan menjadi dasar pembuatan laporan dan dashboard yang digunakan manajemen untuk memantau performa penjualan, mengidentifikasi tren bisnis, serta mendukung pengambilan keputusan yang berbasis data. Selain itu, kamu juga perlu memastikan bahwa data yang disajikan memiliki struktur yang baik sehingga dapat diakses dan digunakan secara efisien oleh berbagai stakeholder di perusahaan.

# **Selayang Pandang**
Hampir semua aktivitas menghasilkan data. Mulai dari data pengguna aplikasi, data transaksi, hingga data hasil analisis, semuanya perlu dikelola dengan baik. Tanpa sistem yang tepat, data akan sulit dicari, tidak rapi, dan berpotensi menimbulkan kesalahan.

<img src="https://cdn.dribbble.com/userupload/42434609/file/original-b7e5f9185d73de1a362bf8644a56a67d.gif" width="40%"><br>
Database hadir sebagai solusi untuk mengelola data secara terstruktur dan efisien. Dengan database, data dapat disimpan dengan rapi, diakses dengan cepat, dan diperbarui sesuai kebutuhan. Hal ini sangat penting dalam pengembangan aplikasi, analisis data, maupun pengambilan keputusan berbasis data.

# **Database**

Database adalah kumpulan data yang tersimpan secara terstruktur sehingga dapat diakses, dikelola, dan diperbarui dengan mudah menggunakan komputer.

Jenis Database :
<ul>
<li><b>Relational Database</b></li>
Database yang menyimpan data dalam bentuk tabel (baris & kolom) dan saling berelasi.

<li><b>Non-Relational Database</b></li>
Database dengan struktur fleksibel, tidak berbasis tabel.<br><br>

<img src="https://www.scylladb.com/wp-content/uploads/differences-between-sql-databases-and-nosql-databases.png" width="50%">
</ul>

# **Tools Database - Google Big Query**

<img src="https://docs.cloud.google.com/static/bigquery/images/gc-bigquery-ready.png" width="40%">

Google BigQuery adalah tools database yang berfungsi sebagai data warehouse di cloud untuk menyimpan dan menganalisis data dalam jumlah sangat besar menggunakan SQL.

Dari sisi database, BigQuery memiliki karakteristik berikut:
* Menyimpan data dalam bentuk tabel seperti database pada umumnya (memiliki dataset, tabel, kolom, dan tipe data).
* Menggunakan SQL (GoogleSQL) untuk melakukan operasi database seperti SELECT, JOIN, GROUP BY, dan analisis data.
* Dioptimalkan untuk analisis data (OLAP), bukan untuk transaksi harian seperti database aplikasi.
* Dikelola sepenuhnya di cloud, sehingga pengguna tidak perlu mengatur server, storage, atau scaling.
* Mampu memproses data sangat besar (hingga terabyte atau petabyte) dengan query yang tetap cepat.

---

### 📝 **1st Challenge** : ***Membuat Project di Google Big Query***

**[Instruksi]** :       
* Buka <a href="console.cloud.google.com">console.cloud.google.com</a>
* Klik bagian Project > Klik New Project
* Lalu isikan `Project Name` dengan *DQLab-Project* (misalkan) lalu setting project id-nya <br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20Create%20Project.png" width="60%">
* Klik button `CREATE`
* Lalu pilih project yang baru dibuat tersebut

---

# **Membuat Dataset**

Dataset di Google BigQuery adalah wadah (container) yang digunakan untuk mengelompokkan tabel, view, dan objek data lainnya dalam satu proyek.

- Penjelasan singkatnya **dataset adalah kumpulan tabel di dalam BigQuery**

<br>

Secara struktur kurang lebih sebagai berikut:
```
Project
   └── Dataset
         ├── Table
         ├── View
         └── External Table
```

---

### 📝 **2nd Challenge** : ***Membuat Dataset di Google Big Query***

Setelah project dibuat, masuk ke bagian Google Big Query dan buat dataset dengan nama `pizza_transaction`

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20Create%20Dataset.png" width="60%">

Jika berhasil maka akan muncul tampilan seperti berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQPizza%20-%20Create%20Dataset%20Success.png" width="40%">

---

# **Membuat Table**

Tabel di dalam database dapat dibuat dengan mengeksekusi perintah berikut:

Membuat tabel dari file (CSV / JSON / Parquet)
* Klik “Create Table” → Source → Upload
* Pilih file (CSV, JSON, Parquet, Avro)
* Pilih Destination Dataset / Table
* Pilih Schema:
* Auto-detect → biar BigQuery deteksi tipe data otomatis
* Edit manually → jika ingin set tipe data spesifik
* Klik “Create Table”

---
### 📝 **3rd Challenge** : ***Menambahkan Data pada Tabel***

Unggah seluruh data pada file `Pizza Transaction Dataset.zip` untuk dimasukan pada tabel, sesuaikan namanya dengan nama filenya dan lakukan hingga semua selesai

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20Create%20Table.png" width="70%">

Jika semua sudah terupload maka akan muncul tampilan seperti berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20Create%20Table%20Success.png" width="30%">


---

# **Tipe Data**

Tipe data adalah klasifikasi jenis nilai yang dapat disimpan dan diproses oleh suatu sistem (seperti bahasa pemrograman atau basis data).
Tipe data menentukan:
* Bentuk data (angka, teks, tanggal, dll)
* Ukuran penyimpanan
* Operasi yang bisa dilakukan
* Aturan validasi data

<br>

Pada SQL beberapa tipe data yang umum digunakan adalah sebagai berikut :
<br><br>

<table>
  <thead>
    <tr>
      <th>Kategori</th>
      <th>Tipe Data</th>
      <th>Deskripsi</th>
      <th>Contoh</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Numeric</td>
      <td>INT64</td>
      <td>Bilangan bulat 64-bit</td>
      <td>100</td>
    </tr>
    <tr>
      <td>Numeric</td>
      <td>FLOAT64</td>
      <td>Bilangan pecahan presisi ganda</td>
      <td>3.1415</td>
    </tr>
    <tr>
      <td>Numeric</td>
      <td>NUMERIC</td>
      <td>Bilangan desimal presisi tinggi (hingga 38 digit)</td>
      <td>12345.67</td>
    </tr>
    <tr>
      <td>Numeric</td>
      <td>BIGNUMERIC</td>
      <td>Bilangan desimal presisi sangat tinggi (hingga 76 digit)</td>
      <td>12345678901234567890.123456</td>
    </tr>
    <tr>
      <td>Character</td>
      <td>STRING</td>
      <td>Teks dengan panjang variabel (UTF-8)</td>
      <td>"Halo BigQuery"</td>
    </tr>
    <tr>
      <td>Binary</td>
      <td>BYTES</td>
      <td>Data biner dengan panjang variabel</td>
      <td>b"abc"</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>DATE</td>
      <td>Tanggal (YYYY-MM-DD)</td>
      <td>2026-01-01</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>TIME</td>
      <td>Waktu tanpa tanggal</td>
      <td>10:30:00</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>DATETIME</td>
      <td>Tanggal dan waktu tanpa zona waktu</td>
      <td>2026-01-01 10:30:00</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>TIMESTAMP</td>
      <td>Titik waktu absolut (UTC)</td>
      <td>2026-01-01 10:30:00 UTC</td>
    </tr>
    <tr>
      <td>Boolean</td>
      <td>BOOL</td>
      <td>Nilai benar atau salah</td>
      <td>TRUE</td>
    </tr>
    <tr>
      <td>JSON</td>
      <td>JSON</td>
      <td>Menyimpan data JSON secara native</td>
      <td>{"nama":"Ani"}</td>
    </tr>
    <tr>
      <td>Complex</td>
      <td>ARRAY</td>
      <td>Daftar elemen dengan tipe data yang sama</td>
      <td>[1,2,3]</td>
    </tr>
    <tr>
      <td>Complex</td>
      <td>STRUCT</td>
      <td>Kumpulan field seperti objek / record</td>
      <td>STRUCT("Ani" AS nama, 20 AS umur)</td>
    </tr>
    <tr>
      <td>Geospatial</td>
      <td>GEOGRAPHY</td>
      <td>Data geospasial seperti titik, garis, dan polygon</td>
      <td>ST_GEOGPOINT(106.8, -6.2)</td>
    </tr>
  </tbody>
</table>

<br>docs : *https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/data-types*

---

#**Set Up**

Untuk dapat menghubungkan Google Colab dengan layanan Google Cloud, khususnya agar bisa mengakses dan mengelola data di BigQuery perlu dilakukan proses autentikasi user terlebih dahulu. Jalankan proses dibawah ini sesuai instruksi

In [ ]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
# Isikan dengan project id masing-masing
project_id = 'dqlabs-project'

# Lalu hubungkan ke Client Big Query
client = bigquery.Client(project = project_id)

Jika semua proses tercentang, maka saat ini colabmu sudah berhasil terhubung ke google BigQuery

---
# **Mengakses Database**

Untuk mengakses dan mengelola database dibutuhkan query. Query adalah sekumpulan perintah yang ditulis menggunakan bahasa SQL untuk berinteraksi dengan database, seperti menampilkan, menambahkan, memperbarui, dan menghapus data sesuai kebutuhan pengguna.

**SQL** (*Structured Query Language*) adalah bahasa yang digunakan untuk berinteraksi dengan database relasional. Dengan SQL, kita dapat mengambil, menambahkan, mengubah, menghapus, dan mengelola data yang tersimpan di dalam database.

<img src="https://sitespirit.co/wp-content/uploads/2024/01/diagram-sql-command-berdasarkan-jenis-query.webp" width="60%">

## **Menampilkan Semua Data pada Satu Tabel**

Untuk dapat menampilkan semua isi (data) pada sebuah tabel di Google BigQuery, eksekusi perintah

```
SELECT * FROM dataset_id.nama_tabel
```

Dalam perintah `SELECT`, tanda bintang (*) digunakan untuk memilih semua kolom dari tabel yang disebutkan. Cara ini merupakan cara cepat untuk mengambil seluruh data tanpa perlu menyebutkan nama-nama kolom satu per satu.

<br>docs : *https://www.postgresql.org/docs/current/sql-select.html*

### 📝 **4th Challenge** : ***Mengakses Data pada Table***

Untuk mempelajari / mengeksplor semua data yang ada pada database `dqpizza`, akan ditampilkan semua data pada tabel berikut :      
- transaction_order
- transaction_order_detail
- master_pizza
- master_pizza_type
- master_customer

In [ ]:
%%bigquery --project $project_id --verbose

-- Tampilkan data `master_pizza_type`
select * from `dqpizza.master_pizza_type`

Executing query with job ID: 39531921-12ae-4d59-a511-b73e2d972eec
Query executing: 0.45s
Job ID 39531921-12ae-4d59-a511-b73e2d972eec successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,pizza_type_id,name,category,ingredients,created_date
0,PIZZA_TYPE_BBQ_CKN,THE BARBECUE CHICKEN PIZZA,CHICKEN,"Barbecued Chicken, Red Peppers, Green Peppers,...",2024-12-31 00:00:00
1,PIZZA_TYPE_CALI_CKN,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ...",2024-12-31 00:00:00
2,PIZZA_TYPE_SOUTHW_CKN,THE SOUTHWEST CHICKEN PIZZA,CHICKEN,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja...",2024-12-31 00:00:00
3,PIZZA_TYPE_CLASSIC_DLX,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2024-12-31 00:00:00
4,PIZZA_TYPE_HAWAIIAN,THE HAWAIIAN PIZZA,CLASSIC,"Sliced Ham, Pineapple, Mozzarella Cheese",2024-12-31 00:00:00
5,PIZZA_TYPE_PEPPERONI,THE PEPPERONI PIZZA,CLASSIC,"Mozzarella Cheese, Pepperoni",2024-12-31 00:00:00
6,PIZZA_TYPE_THE_GREEK,THE GREEK PIZZA,CLASSIC,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",2024-12-31 00:00:00
7,PIZZA_TYPE_BIG_MEAT,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",2024-12-31 00:00:00
8,PIZZA_TYPE_NAPOLITANA,THE NAPOLITANA PIZZA,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",2024-12-31 00:00:00
9,PIZZA_TYPE_CALABRESE,THE CALABRESE PIZZA,SUPREME,"‘Nduja Salami, Pancetta, Tomatoes, Red Onions,...",2024-12-31 00:00:00
10,PIZZA_TYPE_PEPPR_SALAMI,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ...",2024-12-31 00:00:00
11,PIZZA_TYPE_SICILIAN,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives...",2024-12-31 00:00:00
12,PIZZA_TYPE_SPICY_ITAL,THE SPICY ITALIAN PIZZA,SUPREME,"Capocollo, Tomatoes, Goat Cheese, Artichokes, ...",2024-12-31 00:00:00
13,PIZZA_TYPE_SOPPRESSATA,THE SOPPRESSATA PIZZA,Supreme,"Soppressata Salami, Fontina Cheese, Mozzarella...",2024-12-31 00:00:00
14,PIZZA_TYPE_ITAL_VEGGIE,THE ITALIAN VEGETABLES PIZZA,VEGGIE,"Eggplant, Artichokes, Tomatoes, Zucchini, Red ...",2024-12-31 00:00:00
15,PIZZA_TYPE_MEDITERRANEO,THE MEDITERRANEAN PIZZA,VEGGIE,"Spinach, Artichokes, Kalamata Olives, Sun-drie...",2024-12-31 00:00:00
16,PIZZA_TYPE_SPIN_PESTO,THE SPINACH PESTO PIZZA,VEGGIE,"Spinach, Artichokes, Tomatoes, Sun-dried Tomat...",2024-12-31 00:00:00
17,PIZZA_TYPE_SPINACH_FET,THE SPINACH AND FETA PIZZA,VEGGIE,"Spinach, Mushrooms, Red Onions, Feta Cheese, G...",2024-12-31 00:00:00
18,PIZZA_TYPE_CKN_ALFREDO,THE CHICKEN ALFREDO PIZZA,chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",2024-12-31 00:00:00
19,PIZZA_TYPE_CKN_PESTO,THE CHICKEN PESTO PIZZA,chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli...",2024-12-31 00:00:00
20,PIZZA_TYPE_THAI_CKN,THE THAI CHICKEN PIZZA,chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha...",2024-12-31 00:00:00
21,PIZZA_TYPE_ITAL_CPCLLO,THE ITALIAN CAPOCOLLO PIZZA,classic,"Capocollo, Red Peppers, Tomatoes, Goat Cheese,...",2024-12-31 00:00:00
22,PIZZA_TYPE_PEP_MSH_PEP,"THE PEPPERONI, MUSHROOM AND PEPPERS PIZZA",classic,"Pepperoni, Mushrooms, Green Peppers",2024-12-31 00:00:00
23,PIZZA_TYPE_BRIE_CARRE,THE BRIE CARRE PIZZA,supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",2024-12-31 00:00:00
24,PIZZA_TYPE_ITAL_SUPR,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2024-12-31 00:00:00
25,PIZZA_TYPE_PRSC_ARGLA,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella...",2024-12-31 00:00:00
26,PIZZA_TYPE_SPINACH_SUPR,THE SPINACH SUPREME PIZZA,supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",2024-12-31 00:00:00
27,PIZZA_TYPE_FIVE_CHEESE,THE FIVE CHEESE PIZZA,veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2024-12-31 00:00:00
28,PIZZA_TYPE_FOUR_CHEESE,THE FOUR CHEESE PIZZA,veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",2024-12-31 00:00:00
29,PIZZA_TYPE_GREEN_GARDEN,THE GREEN GARDEN PIZZA,veggie,"Spinach, Mushrooms, Tomatoes, Green Olives, Fe...",2024-12-31 00:00:00
30,PIZZA_TYPE_MEXICANA,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2024-12-31 00:00:00
31,PIZZA_TYPE_VEGGIE_VEG,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",2024-12-31 00:00:00

In [ ]:
from IPython.display import HTML

# Manually define descriptions for the columns
column_descriptions = {
    "pizza_type_id": "ID unik untuk jenis pizza",
    "name": "Nama jenis pizza",
    "category": "Kategori jenis pizza (misalnya: ayam, klasik, vegetarian)",
    "ingredients": "Daftar bahan-bahan yang digunakan dalam jenis pizza ini",
    "created_date": "Tanggal dan waktu record ini dibuat"
}

# Construct the HTML table string
html_table_str = "<table>\n"
html_table_str += "  <thead>\n"
html_table_str += "    <tr>\n"
html_table_str += "      <th>Nama Kolom</th>\n"
html_table_str += "      <th>Deskripsi</th>\n"
html_table_str += "    </tr>\n"
html_table_str += "  </thead>\n"
html_table_str += "  <tbody>\n"

# Assuming the columns from the query are available or use the predefined keys
# If a dataframe 'df' was created from the query, you could use df.columns
# For this specific request, we rely on the known schema and the column_descriptions dictionary.

# Get the actual column names from the `master_pizza_type` dataframe if it exists from the previous bigquery magic command
# If `master_pizza_type` dataframe is not directly available, we fall back to keys from column_descriptions

# This assumes the magic command `%%bigquery master_pizza_type` stored the result in a DataFrame named `master_pizza_type`
if 'master_pizza_type' in locals():
    for col_name in master_pizza_type.columns:
        description = column_descriptions.get(col_name, f"Deskripsi belum tersedia untuk kolom '{col_name}'")
        html_table_str += f"    <tr>\n"
        html_table_str += f"      <td>{col_name}</td>\n"
        html_table_str += f"      <td>{description}</td>\n"
        html_table_str += f"    </tr>\n"
else:
    # Fallback if the dataframe is not directly available in locals() (e.g., if bigquery magic didn't store it by name)
    # In this specific context, the bigquery magic command does store it by name, so this path is less likely to be taken.
    print("Warning: 'master_pizza_type' DataFrame not found. Using predefined column names for data dictionary.")
    for col_name, description in column_descriptions.items():
        html_table_str += f"    <tr>\n"
        html_table_str += f"      <td>{col_name}</td>\n"
        html_table_str += f"      <td>{description}</td>\n"

html_table_str += "  </tbody>\n"
html_table_str += "</table>"

display(HTML(html_table_str))

Setelah berhasil mendapatkan data pada table **master_pizza_type**, buat data dictionary dengan bantuan Gemini AI (fitur bawaan pada Google Colab). Contoh prompt yang bisa dilakukan terlampir sebagai berikut :

*"Buatkan data dictionary (dalam bahasa indonesia) berbentuk table html pada tabel dqpizza.master_pizza_type hanya nama kolom dan deskripsinya saja agar bisa langsung di copy di markdown colab"*

<br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20Gemini%20Data%20Dictionary.png" width="100%">

Selain mendefinisikan kolom, perlu diketahui juga **KUALITAS DATA** dari data yang dimiliki.

# **Data Quality**
Ukuran seberapa layak data dipakai untuk tujuan bisnis, analitik, pelaporan, atau operasional. Data berkualitas bukan sekadar “ada”, tetapi benar, lengkap, konsisten, tepat waktu, dan bisa dipercaya. Beberapa dimensi yang paling sering dipakai adalah sebagai berikut :

<img src="https://www.getdbt.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Fwl0ndo6t%2Fmain%2F8111ea89a2d4bf939c59042d140a3834ced0623d-2178x548.png%3Ffit%3Dmax%26auto%3Dformat&w=3840&q=75">

docs : *https://www.getdbt.com/blog/data-quality-framework-choosing*

Jika **Data Quality** menjawab: `Apakah datanya bagus?`
maka **Data Profiling** menjawab: `Seperti apa isi data yang saya miliki?`

Untuk melakukan data profiling, langkah yang dilakukan :

- Install library <a href="ydata-profiling.ydata.ai">ydata-profiling</a> dengan mengeksekusi perintah `pip install ydata-profiling`
- Definisikan data (DataFrame) yang akan diproses
- Import library yang digunakan
- Lakukan proses data profiling
- Periksa hasilnya!

docs : *https://docs.profiling.ydata.ai/latest/*

## **Langkah - Langkah Data Profiling**
* [Langkah 1] - Proses Install Library

In [ ]:
pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 9.3 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 24.8 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 62.1 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 48.2 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 10.2 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.8 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

* [Langkah 2] - Definsikan Data

In [ ]:
%%bigquery master_pizza_type --project {project_id} --verbose

-- Tampilkan data `master_pizza_type`
select * from `dqpizza.master_pizza_type`

Executing query with job ID: 1cf289e5-8cd9-4af0-9724-0a88c90e7d7f
Query executing: 0.60s
Job ID 1cf289e5-8cd9-4af0-9724-0a88c90e7d7f successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:
master_pizza_type

,pizza_type_id,name,category,ingredients,created_date
0,PIZZA_TYPE_BBQ_CKN,THE BARBECUE CHICKEN PIZZA,CHICKEN,"Barbecued Chicken, Red Peppers, Green Peppers,...",2024-12-31 00:00:00
1,PIZZA_TYPE_CALI_CKN,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ...",2024-12-31 00:00:00
2,PIZZA_TYPE_SOUTHW_CKN,THE SOUTHWEST CHICKEN PIZZA,CHICKEN,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja...",2024-12-31 00:00:00
3,PIZZA_TYPE_CLASSIC_DLX,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2024-12-31 00:00:00
4,PIZZA_TYPE_HAWAIIAN,THE HAWAIIAN PIZZA,CLASSIC,"Sliced Ham, Pineapple, Mozzarella Cheese",2024-12-31 00:00:00
5,PIZZA_TYPE_PEPPERONI,THE PEPPERONI PIZZA,CLASSIC,"Mozzarella Cheese, Pepperoni",2024-12-31 00:00:00
6,PIZZA_TYPE_THE_GREEK,THE GREEK PIZZA,CLASSIC,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",2024-12-31 00:00:00
7,PIZZA_TYPE_BIG_MEAT,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",2024-12-31 00:00:00
8,PIZZA_TYPE_NAPOLITANA,THE NAPOLITANA PIZZA,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",2024-12-31 00:00:00
9,PIZZA_TYPE_CALABRESE,THE CALABRESE PIZZA,SUPREME,"‘Nduja Salami, Pancetta, Tomatoes, Red Onions,...",2024-12-31 00:00:00
10,PIZZA_TYPE_PEPPR_SALAMI,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ...",2024-12-31 00:00:00
11,PIZZA_TYPE_SICILIAN,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives...",2024-12-31 00:00:00
12,PIZZA_TYPE_SPICY_ITAL,THE SPICY ITALIAN PIZZA,SUPREME,"Capocollo, Tomatoes, Goat Cheese, Artichokes, ...",2024-12-31 00:00:00
13,PIZZA_TYPE_SOPPRESSATA,THE SOPPRESSATA PIZZA,Supreme,"Soppressata Salami, Fontina Cheese, Mozzarella...",2024-12-31 00:00:00
14,PIZZA_TYPE_ITAL_VEGGIE,THE ITALIAN VEGETABLES PIZZA,VEGGIE,"Eggplant, Artichokes, Tomatoes, Zucchini, Red ...",2024-12-31 00:00:00
15,PIZZA_TYPE_MEDITERRANEO,THE MEDITERRANEAN PIZZA,VEGGIE,"Spinach, Artichokes, Kalamata Olives, Sun-drie...",2024-12-31 00:00:00
16,PIZZA_TYPE_SPIN_PESTO,THE SPINACH PESTO PIZZA,VEGGIE,"Spinach, Artichokes, Tomatoes, Sun-dried Tomat...",2024-12-31 00:00:00
17,PIZZA_TYPE_SPINACH_FET,THE SPINACH AND FETA PIZZA,VEGGIE,"Spinach, Mushrooms, Red Onions, Feta Cheese, G...",2024-12-31 00:00:00
18,PIZZA_TYPE_CKN_ALFREDO,THE CHICKEN ALFREDO PIZZA,chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",2024-12-31 00:00:00
19,PIZZA_TYPE_CKN_PESTO,THE CHICKEN PESTO PIZZA,chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli...",2024-12-31 00:00:00
20,PIZZA_TYPE_THAI_CKN,THE THAI CHICKEN PIZZA,chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha...",2024-12-31 00:00:00
21,PIZZA_TYPE_ITAL_CPCLLO,THE ITALIAN CAPOCOLLO PIZZA,classic,"Capocollo, Red Peppers, Tomatoes, Goat Cheese,...",2024-12-31 00:00:00
22,PIZZA_TYPE_PEP_MSH_PEP,"THE PEPPERONI, MUSHROOM AND PEPPERS PIZZA",classic,"Pepperoni, Mushrooms, Green Peppers",2024-12-31 00:00:00
23,PIZZA_TYPE_BRIE_CARRE,THE BRIE CARRE PIZZA,supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",2024-12-31 00:00:00
24,PIZZA_TYPE_ITAL_SUPR,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2024-12-31 00:00:00
25,PIZZA_TYPE_PRSC_ARGLA,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella...",2024-12-31 00:00:00
26,PIZZA_TYPE_SPINACH_SUPR,THE SPINACH SUPREME PIZZA,supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",2024-12-31 00:00:00
27,PIZZA_TYPE_FIVE_CHEESE,THE FIVE CHEESE PIZZA,veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2024-12-31 00:00:00
28,PIZZA_TYPE_FOUR_CHEESE,THE FOUR CHEESE PIZZA,veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",2024-12-31 00:00:00
29,PIZZA_TYPE_GREEN_GARDEN,THE GREEN GARDEN PIZZA,veggie,"Spinach, Mushrooms, Tomatoes, Green Olives, Fe...",2024-12-31 00:00:00
30,PIZZA_TYPE_MEXICANA,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2024-12-31 00:00:00
31,PIZZA_TYPE_VEGGIE_VEG,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",2024-12-31 00:00:00

* [Langkah 3] - Import Library ydata_profiling

In [ ]:
# Import library yang digunakan
from ydata_profiling import ProfileReport

/tmp/ipykernel_3410/1312677283.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

* [Langkah 4] - Proses Profiling Data

In [ ]:
# Generate Profile Report
profile = ProfileReport(
    master_pizza_type,
    title = "Master Pizza Type Profiling",
    explorative = True
)

# Tampilkan hasilnya
display(profile)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00, 51.78it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

### Anomali / Insight pada `master_pizza_type`

Setelah meninjau laporan profil untuk `master_pizza_type` dan melihat sampel data, berikut adalah anomali yang ditemukan:

1.  **Inkonsistensi Huruf Besar/Kecil pada Kolom `category`:**
    *   Beberapa nilai dalam kolom `category` menggunakan huruf kapital (misalnya, 'CHICKEN', 'CLASSIC'), sementara yang lain menggunakan huruf kecil (misalnya, 'veggie').
    *   **Dampak:** Inkonsistensi ini dapat menyebabkan masalah saat melakukan filter, pengelompokan, atau analisis kategorikal. Sistem mungkin memperlakukan 'veggie' dan 'VEGGIE' sebagai dua kategori yang berbeda padahal seharusnya sama.
    *   **Rekomendasi:** Lakukan standarisasi kapitalisasi (misalnya, konversi semua ke huruf kapital atau semua ke huruf kecil) untuk memastikan konsistensi data.

2.  **Nilai `created_date` yang Seragam (2024-12-31 00:00:00):**
    *   Semua entri dalam kolom `created_date` memiliki nilai yang sama persis (`2024-12-31 00:00:00`). Ini sangat tidak biasa untuk timestamp pembuatan record yang sebenarnya.
    *   **Dampak:** Ini mengindikasikan bahwa kolom ini kemungkinan diisi dengan nilai default, placeholder, atau ada kesalahan dalam proses injeksi data, bukan mencerminkan waktu pembuatan data yang sebenarnya. Informasi waktu pembuatan yang akurat tidak tersedia.
    *   **Rekomendasi:** Periksa proses *data ingestion* atau *ETL* untuk memahami mengapa kolom ini memiliki nilai yang seragam. Jika diperlukan, pertimbangkan untuk menangani kolom ini sebagai indikator status atau mengabaikannya untuk analisis berbasis waktu, kecuali jika ada penjelasan yang valid untuk keseragaman ini.

---

### 📝 **5th Challenge** : ***Data Quality Checking***

Setelah memeriksa secara detail mengenai data `master_pizza_type`, coba lakukan hal yang sama pada keempat tabel data lainnya pada dataset dqpizza yakni :  
- transaction_order
- transaction_order_detail
- master_pizza
- master_customer

#### Data **transaction_order**

In [ ]:
%%bigquery transaction_order --project {project_id} --verbose

-- Tampilkan data `transaction_order`
select * from `dqpizza.transaction_order`

Executing query with job ID: 6cfa5ed7-79fb-4757-ba6c-14a2a1d0ba94
Query executing: 1.39s
Job ID 6cfa5ed7-79fb-4757-ba6c-14a2a1d0ba94 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:
# Generate Profile Report
profile = ProfileReport(
    transaction_order,
    title = "Transaction Order Profiling",
    explorative = True
)

# Tampilkan hasilnya
display(profile)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/9 [00:00<?, ?it/s]
 11%|█         | 1/9 [00:00<00:02,  3.20it/s]
 44%|████▍     | 4/9 [00:00<00:00, 10.85it/s]
 67%|██████▋   | 6/9 [00:05<00:03,  1.16s/it]
100%|██████████| 9/9 [00:05<00:00,  1.57it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Insigh yang ditemukan :

#### Data **transaction_order_detail**

In [ ]:
%%bigquery transaction_order_detail --project {project_id} --verbose

-- Tampilkan data `transaction_order_detail`
select * from `dqpizza.transaction_order_detail`

Executing query with job ID: cd4a9147-90ef-4fc4-8bce-24c4f73820e1
Query executing: 1.50s
Job ID cd4a9147-90ef-4fc4-8bce-24c4f73820e1 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:
# Generate Profile Report
profile = ProfileReport(
    transaction_order_detail,
    title = "Transaction Order Detail Profiling",
    explorative = True
)

# Tampilkan hasilnya
display(profile)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]
 20%|██        | 1/5 [00:00<00:03,  1.14it/s]
100%|██████████| 5/5 [00:01<00:00,  4.63it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

### Anomali / Insight pada `transaction_order_detail`

Setelah meninjau laporan profil untuk `transaction_order_detail`, berikut adalah beberapa poin penting mengenai kualitas data:

1.  **`order_details_id`**: Kolom ini berfungsi sebagai primary key untuk detail pesanan. Pastikan semua nilai unik dan tidak ada nilai yang hilang. Jika ada duplikasi atau nilai kosong, ini mengindikasikan masalah integritas data.

2.  **`order_id`**: Ini adalah foreign key yang menghubungkan ke tabel `transaction_order`. Penting untuk memeriksa:
    *   **Nilai Hilang**: Apakah ada `order_id` yang kosong? Ini berarti ada detail pesanan yang tidak terhubung dengan pesanan induk.
    *   **Integritas Referensial**: Pastikan semua `order_id` yang ada di tabel ini juga ada di tabel `transaction_order`. Jika tidak, berarti ada 'detail pesanan yatim piatu' (orphaned order details).

3.  **`pizza_id`**: Kolom ini adalah foreign key yang menghubungkan ke tabel `master_pizza`. Sama seperti `order_id`:
    *   **Nilai Hilang**: Apakah ada `pizza_id` yang kosong? Ini berarti ada detail pesanan yang tidak merujuk ke jenis pizza yang valid.
    *   **Integritas Referensial**: Pastikan semua `pizza_id` yang ada di tabel ini juga ada di tabel `master_pizza`.

4.  **`quantity`**: Kolom ini menunjukkan jumlah pizza dalam satu detail pesanan.
    *   **Rentang Nilai**: Periksa apakah nilai kuantitas selalu positif dan masuk akal (misalnya, tidak ada 0 atau nilai negatif, dan tidak ada angka yang terlalu besar yang bisa menjadi outlier).
    *   **Distribusi**: Perhatikan distribusi kuantitas. Apakah sebagian besar pesanan hanya satu pizza, atau ada pesanan dengan kuantitas besar?

5.  **`created_date`**: Kolom timestamp ini menunjukkan kapan detail pesanan dibuat.
    *   **Rentang Tanggal**: Periksa rentang tanggal untuk memastikan semua data berada dalam periode waktu yang diharapkan. Adakah tanggal yang di masa depan atau terlalu jauh di masa lalu?
    *   **Konsistensi**: Periksa format tanggal dan waktu. Jika semua `created_date` memiliki nilai yang sama (seperti yang terlihat pada `master_pizza_type`), ini mungkin menunjukkan penggunaan nilai default atau masalah *data ingestion*.

#### Data **master_pizza**

In [ ]:
%%bigquery master_pizza --project {project_id} --verbose

-- Tampilkan data `master_pizza`
select * from `dqpizza.master_pizza`

Executing query with job ID: c4b3d897-d3b5-4c20-b417-2db3ac4a92ff
Query executing: 0.66s
Job ID c4b3d897-d3b5-4c20-b417-2db3ac4a92ff successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:
# Generate Profile Report
profile = ProfileReport(
    master_pizza,
    title = "Master Pizza Profiling",
    explorative = True
)

# Tampilkan hasilnya
display(profile)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 67.99it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

### Anomali / Insight pada `master_pizza`

Setelah meninjau laporan profil untuk `master_pizza`, berikut adalah beberapa poin penting mengenai kualitas data:

1.  **`pizza_id`**: Kolom ini adalah primary key untuk tabel pizza. Pastikan semua nilai unik dan tidak ada nilai yang hilang. Duplikasi atau nilai kosong akan mengindikasikan masalah integritas data.

2.  **`pizza_type_id`**: Kolom ini adalah foreign key yang menghubungkan ke tabel `master_pizza_type`. Penting untuk memeriksa:
    *   **Nilai Hilang**: Apakah ada `pizza_type_id` yang kosong? Ini berarti ada pizza yang tidak terhubung dengan tipe pizza yang valid.
    *   **Integritas Referensial**: Pastikan semua `pizza_type_id` yang ada di tabel ini juga ada di tabel `master_pizza_type`.

3.  **`size`**: Kolom kategorikal ini menunjukkan ukuran pizza (misalnya, S, M, L, XL). Periksa:
    *   **Konsistensi Nilai**: Pastikan tidak ada variasi penulisan yang tidak standar (misalnya, 's' dan 'S' dianggap berbeda).
    *   **Distribusi**: Perhatikan distribusi ukuran pizza.

4.  **`price` dan `production_cost`**: Kolom ini menunjukkan harga jual dan biaya produksi pizza.
    *   **Tipe Data dan Format**: Terlihat bahwa nilai pada kolom ini masih dalam format string dengan awalan 'IDR' (misalnya, 'IDR123525'). Ini berarti kolom ini perlu dikonversi ke tipe data numerik (integer atau float) terlebih dahulu sebelum dapat digunakan untuk perhitungan matematis.
    *   **Rentang Nilai**: Pastikan semua nilai positif dan masuk akal. Periksa outlier atau nilai nol/negatif yang mungkin tidak valid.

5.  **`created_date`**: Kolom timestamp ini menunjukkan kapan data pizza dibuat.
    *   **Konsistensi Nilai**: Sama seperti `master_pizza_type`, jika semua `created_date` memiliki nilai yang sama (`2024-12-31 00:00:00`), ini menunjukkan penggunaan nilai default atau adanya masalah dalam proses *data ingestion*. Hal ini mengurangi nilai historis dari kolom ini.
    *   **Rentang Tanggal**: Periksa rentang tanggal untuk memastikan tidak ada tanggal yang tidak valid atau di masa depan.

6.  **`updated_date`**: Kolom ini bisa berisi nilai null jika data belum pernah diperbarui. Periksa konsistensi format dan rentang tanggal jika ada nilai.

#### Data **master_customer**

In [ ]:
%%bigquery master_customer --project {project_id} --verbose

-- Tampilkan data `master_customer`
select * from `dqpizza.master_customer`

Executing query with job ID: fde13e16-b94a-466e-b781-6ca30f607dc8
Query executing: 0.53s
Job ID fde13e16-b94a-466e-b781-6ca30f607dc8 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:
# Generate Profile Report
profile = ProfileReport(
    master_customer,
    title = "Master Customer Profiling",
    explorative = True
)

# Tampilkan hasilnya
display(profile)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
100%|██████████| 8/8 [00:00<00:00, 37.86it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

### Anomali / Insight pada `master_customer`

Setelah meninjau laporan profil untuk `master_customer`, berikut adalah beberapa poin penting mengenai kualitas data:

1.  **`customer_id`**: Kolom ini berfungsi sebagai primary key untuk pelanggan. Pastikan semua nilai unik dan tidak ada nilai yang hilang. Duplikasi atau nilai kosong akan mengindikasikan masalah integritas data yang serius.

2.  **`customer_name`**: Ini adalah kolom teks. Periksa:
    *   **Konsistensi Penulisan**: Apakah ada variasi penulisan nama yang sama (misalnya, 'John Doe' vs. 'john doe')? Laporan profil dapat menunjukkan jumlah nilai unik dan paling sering muncul.
    *   **Nilai yang Hilang**: Apakah ada pelanggan tanpa nama?
    *   **Outlier Teks**: Periksa apakah ada nama yang terlalu panjang atau tidak relevan, yang mungkin mengindikasikan *data entry error*.

3.  **`gender`**: Kolom kategorikal ini harus memiliki nilai yang terbatas dan konsisten (misalnya, 'L'/'P' atau 'Male'/'Female'). Periksa:
    *   **Variasi Nilai**: Apakah ada variasi penulisan yang tidak standar (misalnya, 'L', 'l', 'Laki-laki', 'P', 'p', 'Perempuan')?
    *   **Distribusi**: Perhatikan distribusi jenis kelamin untuk memastikan keseimbangan atau sesuai dengan ekspektasi bisnis.

4.  **`birth_date`**: Kolom tanggal lahir.
    *   **Rentang Tanggal**: Periksa rentang `birth_date`. Adakah tanggal lahir di masa depan atau tanggal yang secara tidak realistis terlalu jauh di masa lalu? Ini bisa mengindikasikan *data entry error*.
    *   **Nilai Hilang**: Apakah ada pelanggan tanpa tanggal lahir?

5.  **`phone_number` dan `email`**: Kolom informasi kontak.
    *   **Format Validasi**: Laporan profil dapat menunjukkan pola umum. Perhatikan apakah ada format yang tidak standar atau nilai yang tidak valid (misalnya, email tanpa '@' atau '.com', nomor telepon dengan panjang yang tidak wajar).
    *   **Nilai Hilang**: Keterisian kedua kolom ini penting untuk komunikasi dengan pelanggan. Periksa persentase nilai yang hilang.
    *   **Duplikasi**: Meskipun `customer_id` harus unik, duplikasi nomor telepon atau email bisa mengindikasikan masalah data atau entri ganda untuk pelanggan yang sama.

6.  **`open_date`**: Tanggal pelanggan membuka akun/pertama kali tercatat.
    *   **Rentang Tanggal**: Periksa rentang tanggal ini. Apakah ada tanggal di masa depan atau yang terlalu jauh di masa lalu?
    *   **Kesesuaian**: `open_date` seharusnya tidak lebih lambat dari `created_date`.

7.  **`created_date` dan `updated_date`**: Kolom timestamp ini menunjukkan kapan record pelanggan dibuat dan terakhir diperbarui.
    *   **Konsistensi Nilai**: Jika semua `created_date` memiliki nilai yang sama (`2025-09-11 11:12:13`), seperti yang terlihat pada `master_pizza_type` dan `master_pizza`, ini menunjukkan penggunaan nilai default atau adanya masalah dalam proses *data ingestion*. Hal ini mengurangi nilai historis dari kolom ini.
    *   **`updated_date`** mungkin memiliki nilai `null` jika record tidak pernah diperbarui.

---

# **ERD**

Data biasanya disimpan di berbagai tabel atau sistem yang berbeda pada RDBMS (Relational Database Management System). Untuk membantu memahami struktur dan hubungan data sebelum melakukan analisis SQL, biasa digunakan ERD (Entity Relationship Diagram).

**ERD** adalah diagram yang digunakan untuk menggambarkan struktur hubungan antar data dalam sebuah database. Langkah-langkah pembuatan ERD adalah sebagai berikut :

* Untuk membuat ERD pada data Pizza Transaction dengan bantuan AI, buka situs https://www.eraser.io/ai/erd-generator

* Ketikan prompt: *"Sebuah table bernama trx_order_detail memiliki kolom 'order_details_id', 'order_id', 'pizza_id', 'quantity', 'created_date'. Table dengan nama trx_order memiliki kolom 'order_id', 'customer_id', 'order_maker_id', 'order_date', 'order_time', 'completion_time', 'is_complain', 'complain_detail', 'created_date'. Kemudian mst_pizza_type memiliki kolom 'pizza_type_id', 'name', 'category', 'ingredients', 'created_date', 'updated_date' lalu tabel mst_pizza memiliki kolom 'pizza_id', 'pizza_type_id', 'size', 'price', 'production_cost', 'created_date', 'updated_date' dan table mst_customer memiliki kolom 'customer_id', 'customer_name', 'gender', 'birth_date', 'phone_number', 'email', 'open_date', 'created_date', 'updated_date'. Buatkan ERD nya!"*

* Jika berhasil maka akan tampil seperti gambar berikut <img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/ERD%20-%20Pizza.jpg" width="60%">

* Dengan terbentuknya ERD data DQPizza Transaction maka struktur data menjadi lebih jelas dan terorganisir, sehingga hubungan antar tabel dapat dipahami dengan mudah. Hal ini memudahkan proses analisis data menggunakan SQL, terutama dalam melakukan join antar tabel untuk menghasilkan informasi transaksi yang utuh.

---

**Written By :** <br>
<a href="https://linkedin.com/in/bachtiyarma"><img alt="Linked In Link" src="https://img.shields.io/badge/-Bachtiyar%20M.%20Arief-0072b1?style=for-the-badge&logo=None&logoColor=white" align="left"/></a>

<br><br>**for :**

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>