<a href="https://colab.research.google.com/github/refianP13/Data-Analyst/blob/main/Copy_of_DQLab_Conditions_%26_Aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><span style='color:#0B2F9F'>Pengantar</span></b>

Dalam analisis data, penting untuk mampu menyaring dan merangkum informasi agar hasil yang diperoleh benar-benar sesuai dengan tujuan yang ingin dicapai. Dengan kemampuan menyaring data, seorang analis dapat fokus hanya pada informasi yang relevan, sementara proses merangkum membantu melihat gambaran besar dari data yang ada. Kedua langkah ini memungkinkan data yang semula rumit menjadi lebih sederhana, terarah, dan bermakna. Dengan memahami cara memilih dan mengelompokkan informasi secara tepat, analis dapat bekerja lebih efisien dalam menemukan pola, menjawab pertanyaan penting, dan menyajikan kesimpulan yang akurat.

# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [ ]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
# Buat BigQuery client
project_id = ''
client = bigquery.Client(project = project_id)

<a id="A"></a>
# <b>A. <span style='color:#0B2F9F'><code>WHERE</code></span></b>

Klausa `WHERE` dalam SQL digunakan untuk menyaring baris data dalam query berdasarkan kondisi tertentu. Cara ini digunakan untuk menentukan kriteria yang harus dipenuhi agar baris data muncul dalam hasil query. Perintah `WHERE` dapat digunakan untuk menyaring nilai :

<ul>
<li>Berdasarkan Kondisi Tertentu</li>
<li>Berdasarkan Beberapa Kondisi</li>
<li>Menggunakan Pola Pencocokan</li>
<li>Menggunakan Rentang Nilai</li>
<li>Berdasarkan Kumpulan Nilai</li>
<li>Berdasarkan Nilai Null</li>
</ul>

<a id="A.1."></a>
## <b>A.1. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Kondisi Tertentu</span></b>

Untuk melakukan penyaringan nilai berdasarkan kondisi tertentu dapat menggunakan <b>Comparison Operators</b>. Operator perbandingan (<i>comparison operators</i>) dalam SQL digunakan untuk membandingkan nilai-nilai dan menentukan bagaimana data memenuhi kondisi tertentu. Operator pembanding pada SQL disimbolkan dengan beberapa tanda berikut
<br><br>
<table border="1">
    <tr>
        <th>Tanda</th>
        <th>Deskripsi</th>
        <th>Contoh</th>
    </tr>
    <tr>
        <td>=</td>
        <td>Sama dengan (<i>Equals</i>)</td>
        <td>A = B</td>
    </tr>
    <tr>
        <td><></td>
        <td>Tidak Sama dengan (<i>Not Equals</i>)</td>
        <td>A <> B</td>
    </tr>
    <tr>
        <td><</td>
        <td>Kurang dari (<i>Less than</i>)</td>
        <td>A < B</td>
    </tr>
    <tr>
        <td>></td>
        <td>Lebih dari (<i>More than</i>)</td>
        <td>A > B</td>
    </tr>
    <tr>
        <td><=</td>
        <td>Kurang dari sama dengan (<i>Less than or Equals To</i>)</td>
        <td>A <= B</td>
    </tr>
    <tr>
        <td>>=</td>
        <td>Lebih dari sama dengan (<i>More than or Equals To</i>)</td>
        <td>A >= B</td>
    </tr>
</table>

<br>Kemudian gunakan operator pembanding tersebut kedalam sebuah kondisi <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Where%201.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Manajemen menemukan fakta bahwa tanggal 27 November 2024 merupakan tanggal terbanyak pelanggan mengajukan komplain ke DQPizza. Tampilkan semua data di tabel orders pada tanggal tersebut!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX019412,CUST001128,EMP000208,11/27/2024,12:15:07,12:25:22,0,None
1,TRX019413,CUST007482,EMP000208,11/27/2024,12:22:17,12:44:25,0,None
2,TRX019414,CUST007656,EMP000208,11/27/2024,12:24:55,12:52:17,0,None
3,TRX019439,CUST004778,EMP000208,11/27/2024,15:58:05,16:19:03,0,None
4,TRX019440,CUST003553,EMP000208,11/27/2024,15:58:19,16:17:11,0,None
...,...,...,...,...,...,...,...,...
110,TRX019464,CUST004354,EMP000756,11/27/2024,18:40:51,19:03:30,1,Pizza was burnt
111,TRX019406,CUST003549,EMP000231,11/27/2024,11:46:40,12:07:03,1,Received wrong pizza
112,TRX019488,CUST008535,EMP000646,11/27/2024,20:26:55,20:55:35,1,Received wrong pizza
113,TRX019429,CUST006843,EMP000295,11/27/2024,14:04:02,14:20:55,1,Wrong pizza size
114,TRX019443,CUST005205,EMP000665,11/27/2024,16:05:07,16:29:58,1,Wrong pizza size

#### <i><b><span style='color:#55679C'>Quest</span> : Manajemen menduga bahwa komplain sering terjadi pada saat dinner (asumsikan dinner mulai jam 6 p.m.), tampilkan data transaksi di table orders untuk kolom order_id, customer_id, order_date, order_time, is_complain saja </b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

       order_id customer_id  order_date order_time  is_complain
0     TRX021342  CUST005956  12/31/2024   20:02:57            1
1     TRX021320  CUST005205  12/31/2024   18:09:28            0
2     TRX021317  CUST002637  12/31/2024   18:01:42            0
3     TRX021347  CUST003549  12/31/2024   21:14:37            0
4     TRX021348  CUST007931  12/31/2024   21:23:10            0
...         ...         ...         ...        ...          ...
7934  TRX000050  CUST004778  01/01/2024   18:41:01            1
7935  TRX000068  CUST009381  01/01/2024   22:07:32            1
7936  TRX000065  CUST007443  01/01/2024   21:16:00            0
7937  TRX000063  CUST007747  01/01/2024   20:51:42            0
7938  TRX000057  CUST008422  01/01/2024   19:10:51            0

[7939 rows x 5 columns]

<a id="A.2."></a>
## <b>A.2. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Beberapa Kondisi</span></b>

Untuk melakukan penyaringan nilai berdasarkan beberapa kondisi dapat menggunakan <b>Logical Operators</b>. Operator logika (<i>logical operator</i>) adalah simbol atau kata kunci yang digunakan untuk menghubungkan dua atau lebih ekspresi logis dan menghasilkan nilai logis baru berdasarkan operasi tersebut. Operator logika pada SQL disimbolkan dengan beberapa tanda berikut
<br><br>
<table border="1">
    <tr>
        <th>Tanda</th>
        <th>Deskripsi</th>
        <th>Kondisi</th>
        <th>Contoh</th>
    </tr>
    <tr>
        <td><b>AND</b></td>
        <td>Operator penghubung 'DAN'</td>
        <td><i>Statement</i> bernilai benar jika keduanya benar / terpenuhi,<br>jika tidak demikian maka bernilai salah</td>
        <td>Condition 1 <b>AND</b> Condition 2</td>
    </tr>
    <tr>
        <td><b>OR</b></td>
        <td>Operator penghubung 'ATAU'</td>
        <td><i>Statement</i> bernilai salah jika keduanya salah / tidak terpenuhi,<br>jika tidak demikian maka bernilai benar</td>
        <td>Condition 1 <b>OR</b> Condition 2</td>
    </tr>
    <tr>
        <td><b>NOT</b></td>
        <td>Operator 'BUKAN'</td>
        <td>Operator ini membalikkan nilai logis dari ekspresi yang dioperasikan</td>
        <td><b>NOT</b> Condition 1</td>
    </tr>
</table>
<br><br>
Saat digunakan, untuk menyaring dua atau lebih pernyataan dengan operator logika akan berlaku kriteria sebagai berikut
<br><br>
<table border="1">
    <tr>
        <th>Condition 1</th>
        <th>Condition 2</th>
        <th>Condition 1 <span style='color:#55679C'>AND</span> Condition 2</th>
        <th>Condition 1 <span style='color:#55679C'>OR</span> Condition 2</th>
    </tr>
    <tr>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
    </tr>
</table>

Saat query dijalankan, hanya output yang bernilai benar saja yang akan ditampilkan.

<br>Kemudian gunakan operator pembanding tersebut kedalam sebuah kondisi <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Where%202.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua data transaksi yang di komplain pada tabel orders pada tanggal 27 November 2024 </b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX019460,CUST008782,EMP000302,11/27/2024,18:13:40,18:38:58,1,Dough undercooked
1,TRX019496,CUST004547,EMP000646,11/27/2024,20:52:37,21:03:29,1,Dough undercooked
2,TRX019442,CUST001988,EMP000286,11/27/2024,16:05:00,16:25:23,1,Missing toppings
3,TRX019476,CUST005429,EMP000560,11/27/2024,19:13:38,19:34:10,1,Missing toppings
4,TRX019458,CUST005429,EMP000665,11/27/2024,17:58:06,18:23:04,1,Missing toppings
5,TRX019441,CUST004293,EMP000302,11/27/2024,16:00:42,16:17:57,1,Order took too long
6,TRX019497,CUST009381,EMP000560,11/27/2024,20:54:24,21:09:01,1,Order took too long
7,TRX019465,CUST004293,EMP000208,11/27/2024,18:41:24,19:02:00,1,Pizza was burnt
8,TRX019438,CUST004537,EMP000646,11/27/2024,15:46:06,16:13:26,1,Pizza was burnt
9,TRX019433,CUST004392,EMP000756,11/27/2024,14:52:48,15:13:41,1,Pizza was burnt
10,TRX019464,CUST004354,EMP000756,11/27/2024,18:40:51,19:03:30,1,Pizza was burnt
11,TRX019406,CUST003549,EMP000231,11/27/2024,11:46:40,12:07:03,1,Received wrong pizza
12,TRX019488,CUST008535,EMP000646,11/27/2024,20:26:55,20:55:35,1,Received wrong pizza
13,TRX019429,CUST006843,EMP000295,11/27/2024,14:04:02,14:20:55,1,Wrong pizza size
14,TRX019443,CUST005205,EMP000665,11/27/2024,16:05:07,16:29:58,1,Wrong pizza size

#### <i><b><span style='color:#55679C'>Quest</span> : Sepertinya komplain yang paling banyak terjadi di tanggal 27 November 2024 adalah pizza yang kegosongan atau topping yang kelupaan. Coba tampilkan data dengan kategori yang disebutkan lalu urutkan berdasarkan jam pemesanan!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX019433,CUST004392,EMP000756,11/27/2024,14:52:48,15:13:41,1,Pizza was burnt
1,TRX019438,CUST004537,EMP000646,11/27/2024,15:46:06,16:13:26,1,Pizza was burnt
2,TRX019442,CUST001988,EMP000286,11/27/2024,16:05:00,16:25:23,1,Missing toppings
3,TRX019458,CUST005429,EMP000665,11/27/2024,17:58:06,18:23:04,1,Missing toppings
4,TRX019464,CUST004354,EMP000756,11/27/2024,18:40:51,19:03:30,1,Pizza was burnt
5,TRX019465,CUST004293,EMP000208,11/27/2024,18:41:24,19:02:00,1,Pizza was burnt
6,TRX019476,CUST005429,EMP000560,11/27/2024,19:13:38,19:34:10,1,Missing toppings

<a id="A.3."></a>
## <b>A.3. <span style='color:#0B2F9F'>Menyaring Nilai Menggunakan Pola Pencocokan</span></b>

SQL telah mendukung operator dan fungsi yang memungkinkan untuk melakukan pencocokan pola pada sebuah teks. Untuk melakukan hal ini dapat menggunakan query `LIKE` dengan bantuan tanda <b>Wildcard (%)</b>. Tanda <b>Wildcard (%)</b>. Wildcard memungkinkan untuk mencari data dengan pola yang tidak pasti atau variatif pada sebuah teks. Contoh :

Sebuah data karyawan memiliki kolom nama, terdapat nama Ilham, Kurnia, Bachtiyar, Baim, Ridho dan Deki
<ul>
    <li>Untuk mencari nama yang diawali huruf B, gunakan sintaks <code>WHERE nama LIKE 'B%'</code>.<br>Nama yang cocok : Bachtiyar & Baim</li><br>
    <li>Untuk mencari nama yang diakhiri dengan huruf m, gunakan sintaks <code>WHERE nama LIKE '%m'</code>.<br>Nama yang cocok : Ilham & Baim</li><br>
    <li>Untuk mencari nama yang diawali huruf B namun diakhiri dengan m, gunakan sintaks <code>WHERE nama LIKE 'B%m'</code>.<br>Nama yang cocok : Baim</li>
</ul>

<br>Kemudian gunakan pola pencocokan tersebut kedalam sebuah kondisi <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Where%203.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua nama menu pizza yang mengandung bayam!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,pizza_type_id,name,category,ingredients
0,PIZZA_TYPE_CALI_CKN,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
1,PIZZA_TYPE_MEDITERRANEO,THE MEDITERRANEAN PIZZA,VEGGIE,"Spinach, Artichokes, Kalamata Olives, Sun-drie..."
2,PIZZA_TYPE_SPIN_PESTO,THE SPINACH PESTO PIZZA,VEGGIE,"Spinach, Artichokes, Tomatoes, Sun-dried Tomat..."
3,PIZZA_TYPE_SPINACH_FET,THE SPINACH AND FETA PIZZA,VEGGIE,"Spinach, Mushrooms, Red Onions, Feta Cheese, G..."
4,PIZZA_TYPE_CKN_PESTO,THE CHICKEN PESTO PIZZA,chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
5,PIZZA_TYPE_SPINACH_SUPR,THE SPINACH SUPREME PIZZA,supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti..."
6,PIZZA_TYPE_GREEN_GARDEN,THE GREEN GARDEN PIZZA,veggie,"Spinach, Mushrooms, Tomatoes, Green Olives, Fe..."
7,PIZZA_TYPE_VEGGIE_VEG,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."

<a id="A.4."></a>
## <b>A.4. <span style='color:#0B2F9F'>Menyaring Nilai Menggunakan Rentang Nilai</span></b>

Selain menggunakan operator pembanding, dapat juga menggunakan query `BETWEEN` untuk mendapatkan nilai pada rentang tertentu. Untuk menyingkat penulisan <code>nilai1 <= nama_kolom AND nama_kolom <= nilai2</code> dapat menggunakan alternatif <code>nama_kolom BETWEEN nilai1 AND nilai2</code>
<br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Where%205.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Manajemen membutuhkan seluruh data transaksi pada bulan November 2024 untuk dievaluasi. Agar memudahkan proses evaluasi, urutkan berdasarkan tanggal dan waktu transaksi</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX017879,CUST001029,EMP000208,11/01/2024,11:40:19,12:08:32,0,None
1,TRX017880,CUST004547,EMP000295,11/01/2024,12:12:20,12:37:10,0,None
2,TRX017881,CUST003406,EMP000231,11/01/2024,12:23:50,12:42:05,0,None
3,TRX017882,CUST008987,EMP000665,11/01/2024,12:31:08,12:41:40,0,None
4,TRX017883,CUST006333,EMP000665,11/01/2024,12:38:50,12:53:55,0,None
...,...,...,...,...,...,...,...,...
1787,TRX019666,CUST003319,EMP000231,11/30/2024,21:30:20,21:58:28,0,None
1788,TRX019667,CUST003549,EMP000560,11/30/2024,21:32:20,21:50:57,0,None
1789,TRX019668,CUST007656,EMP000231,11/30/2024,21:46:27,22:03:41,0,None
1790,TRX019669,CUST009740,EMP000646,11/30/2024,22:26:23,22:38:48,0,None
1791,TRX019670,CUST007809,EMP000208,11/30/2024,22:39:18,22:53:58,0,None

<a id="A.5."></a>
## <b>A.5. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Kumpulan Nilai</span></b>

Untuk melakukan penyaringan nilai berdasarkan kumpulan nilai dapat menggunakan <b>Operator Keanggotaan</b>. Operator keanggotaan (<i>membership operators</i>) dalam SQL digunakan untuk digunakan untuk memeriksa apakah suatu nilai cocok dengan nilai apa pun dalam daftar atau subkueri tertentu. Contoh penggunaan operator keanggotaan pada SQL adalah sebagai berikut :

Sebuah data karyawan memiliki kolom nama, terdapat nama Ilham, Kurnia, Bachtiyar, Baim, Ridho dan Deki
<ul>
    <li>Untuk mencari nama Ilham dan Ridho, gunakan sintaks <code>WHERE nama IN ('Ilham', 'Ridho')</code>.<br>Output : Ilham, Ridho</li><br>
    <li>Untuk mencari nama <b>SELAIN</b> Ilham dan Ridho, gunakan sintaks <code>WHERE nama NOT IN ('Ilham', 'Ridho')</code>.<br>Output : Kurnia, Bachtiyar, Baim, Deki</li>
</ul>

<br>Kemudian gunakan operator keanggotaan tersebut kedalam sebuah kondisi <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Where%204.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Manajemen perlu mengevaluasi kinerja pegawai dengan nomor pegawai EMP000437, EMP000665 dan EMP000231 terkait banyaknya komplain yang pernah terjadi. Tunjukan data transaksi di tabel orders untuk dua pegawai tersebut namun hanya ketika mereka mendapatkan komplain!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX002315,CUST006964,EMP000231,02/08/2024,14:33:52,15:00:36,1,Dough undercooked
1,TRX003080,CUST005449,EMP000231,02/21/2024,12:23:18,12:44:40,1,Dough undercooked
2,TRX003674,CUST001128,EMP000231,03/03/2024,17:58:31,18:23:51,1,Dough undercooked
3,TRX011663,CUST006333,EMP000231,07/14/2024,15:48:22,16:15:34,1,Dough undercooked
4,TRX011706,CUST007768,EMP000231,07/15/2024,12:34:23,12:46:08,1,Dough undercooked
...,...,...,...,...,...,...,...,...
664,TRX018087,CUST003553,EMP000665,11/04/2024,22:09:13,22:19:13,1,Wrong pizza size
665,TRX018554,CUST007156,EMP000665,11/12/2024,20:51:27,21:03:38,1,Wrong pizza size
666,TRX019443,CUST005205,EMP000665,11/27/2024,16:05:07,16:29:58,1,Wrong pizza size
667,TRX019993,CUST005127,EMP000665,12/06/2024,15:02:06,15:28:17,1,Wrong pizza size
668,TRX021166,CUST007562,EMP000665,12/27/2024,17:35:20,17:51:38,1,Wrong pizza size

#### <i><b><span style='color:#55679C'>Quest</span> : Manajemen perlu mengevaluasi kinerja pegawai dengan nomor pegawai EMP000437, EMP000665 dan EMP000231 terkait banyaknya komplain yang pernah terjadi. Tunjukan data transaksi di tabel orders untuk dua pegawai tersebut namun hanya ketika mereka mendapatkan komplain selain tanggal 1 November 2024 atau 27 November 2024!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX002315,CUST006964,EMP000231,02/08/2024,14:33:52,15:00:36,1,Dough undercooked
1,TRX003080,CUST005449,EMP000231,02/21/2024,12:23:18,12:44:40,1,Dough undercooked
2,TRX003674,CUST001128,EMP000231,03/03/2024,17:58:31,18:23:51,1,Dough undercooked
3,TRX011663,CUST006333,EMP000231,07/14/2024,15:48:22,16:15:34,1,Dough undercooked
4,TRX011706,CUST007768,EMP000231,07/15/2024,12:34:23,12:46:08,1,Dough undercooked
...,...,...,...,...,...,...,...,...
660,TRX016973,CUST007854,EMP000665,10/15/2024,13:39:34,13:51:39,1,Wrong pizza size
661,TRX018087,CUST003553,EMP000665,11/04/2024,22:09:13,22:19:13,1,Wrong pizza size
662,TRX018554,CUST007156,EMP000665,11/12/2024,20:51:27,21:03:38,1,Wrong pizza size
663,TRX019993,CUST005127,EMP000665,12/06/2024,15:02:06,15:28:17,1,Wrong pizza size
664,TRX021166,CUST007562,EMP000665,12/27/2024,17:35:20,17:51:38,1,Wrong pizza size

<a id="A.6."></a>
## <b>A.6. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Nilai NULL</span></b>

`NULL` adalah nilai khusus yang digunakan untuk menunjukkan bahwa data tidak tersedia, tidak diketahui, atau tidak relevan. Untuk mencari data yang NULL pada SQL gunakan perintah berikut :

<ul>
    <li>Untuk mencari data yang kosong atau NULL, gunakan sintaks <code>WHERE nama_kolom IS NULL</code></li><br>
    <li>Untuk mencari data yang tidak kosong atau NOT NULL, gunakan sintaks <code>WHERE nama_kolom IS NOT NULL</code></li><br>
</ul>

Untuk menggunakannya, eksekusi query berikut <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Where%206.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Untuk melakukan validitas data, tampilkan data pada order_details yang order_details_id kosong!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

...

  order_details_id   order_id             pizza_id  quantity
0             None  TRX006536  PIZZA_CKN_ALFREDO_L         1
1             None  TRX006538     PIZZA_MEXICANA_M         1
2             None  TRX006537   PIZZA_VEGGIE_VEG_M         1
3             None  TRX006505   PIZZA_VEGGIE_VEG_S         1

<a id="B"></a>
# <b>B. <span style='color:#0B2F9F'><code>CASE - WHEN</code></b>

`CASE` adalah sebuah ekspresi dalam SQL yang digunakan untuk melakukan logika kondisional. `CASE` sering digunakan untuk mengubah nilai yang ditampilkan dalam query berdasarkan kondisi tertentu. Untuk dapat menggunakan perintah `CASE` gunakan sintaks umum berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Case%20When.png" width="40%">

#### <i><b><span style='color:#55679C'>Quest</span> : Manajemen perlu mengelompokkan detail komplain yang pernah terjadi sesuai kriteria berikut </b></i><br>

<table border="1">
    <tr>
        <th>Complain Type</th>
        <th>Complain Detail</th>
    </tr>
    <tr>
        <td>Order Issue</td>
        <td>Drink was missing</td>
    </tr>
    <tr>
        <td>Order Issue</td>
        <td>Wrong pizza size</td>
    </tr>
    <tr>
        <td>Order Issue</td>
        <td>Received wrong pizza</td>
    </tr>
    <tr>
        <td>Food Problem</td>
        <td>Dough undercooked</td>
    </tr>
    <tr>
        <td>Food Problem</td>
        <td>Missing toppings</td>
    </tr>
    <tr>
        <td>Food Problem</td>
        <td>Pizza was burnt</td>
    </tr>
    <tr>
        <td>Service Issue</td>
        <td>Order took too long</td>
    </tr>
    <tr>
        <td>Service Issue</td>
        <td>Rude staff at counter</td>
    </tr>
</table><br>

<b><i>Tampilkan kolom order_id, order_maker_id, order_date, complain_detail dan complain_type (kolom baru hasil pengelompokan diatas) pada tabel orders!</i></b>

In [ ]:
%%bigquery --project {project_id} --verbose

...

        order_id order_maker_id  order_date   complain_detail complain_type
0      TRX000026      EMP000208  01/01/2024              None          None
1      TRX000037      EMP000208  01/01/2024              None          None
2      TRX000057      EMP000208  01/01/2024              None          None
3      TRX000077      EMP000208  01/02/2024              None          None
4      TRX000087      EMP000208  01/02/2024              None          None
...          ...            ...         ...               ...           ...
21345  TRX009714      EMP000756  06/12/2024  Wrong pizza size   Order Issue
21346  TRX011127      EMP000756  07/05/2024  Wrong pizza size   Order Issue
21347  TRX011178      EMP000756  07/06/2024  Wrong pizza size   Order Issue
21348  TRX012098      EMP000756  07/21/2024  Wrong pizza size   Order Issue
21349  TRX019645      EMP000756  11/30/2024  Wrong pizza size   Order Issue

[21350 rows x 5 columns]

<a id="C"></a>
# <b>C. <span style='color:#0B2F9F'><code>AGGREGATION</code></b>

Fungsi agregat atau <b>Aggregation</b> adalah fungsi yang melakukan perhitungan pada sekumpulan nilai dan mengembalikan satu nilai hasil perhitungan tersebut. Fungsi agregat SQL yang paling umum digunakan adalah:
<br><br>
<table border="1">
    <tr>
        <th>Fungsi Agregat</th>
        <th>Deskripsi</th>
    </tr>
    <tr>
        <td><b>MIN( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>nilai terkecil</span> dalam kolom yang dipilih.</td>
    </tr>
    <tr>
        <td><b>MAX( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>nilai terbesar</span> dalam kolom yang dipilih.</td>
    </tr>
    <tr>
        <td><b>COUNT( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>jumlah baris</span> dalam suatu set</td>
    </tr>
    <tr>
        <td><b>SUM( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>jumlah total</span> dari kolom numerik.</td>
    </tr>
    <tr>
        <td><b>AVG( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>nilai rata-rata</span> dari kolom numerik.</td>
    </tr>
</table>

<br>Gunakan fungsi aggregasi tersebut dengan mengikuti sintaks <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Aggregation.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Ada berapa jumlah customer DQPizza yang telah ter-record? </b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

...

   jumlah_customer
0              137

#### <i><b><span style='color:#55679C'>Quest</span> : Selama tahun 2024, ada berapa kali transaksi dan berapa komplain pernah terjadi? Sertakan presentasenya! </b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

...

   total_transaksi  jumlah_komplain  presentase_komplain
0            21350             2135                 10.0

<a id="D"></a>
# <b>D. <span style='color:#0B2F9F'><code>GROUP BY</code></b>

Fungsi agregat sering digunakan bersama dengan klausa GROUP BY pada pernyataan SELECT. Klausa GROUP BY membagi hasil query menjadi beberapa kelompok nilai, dan fungsi agregat dapat digunakan untuk mengembalikan satu nilai untuk setiap kelompok.
<br><br>
Contoh simulasi perhitungannya adalah sebagai berikut :
<br><br>
<img src="https://wesmckinney.com/book/images/pda3_1001.png" width="25%" height="1%">

<br>Gunakan fungsi aggregasi dengan pengelompokan dengan mengikuti sintaks <br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Group%20By.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Untuk mengetahui demografi pelanggan, hitung total pelanggan lalu kelompokan berdasarkan gender-nya! </b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

...

  gender  total_pelanggan
0      F               70
1      M               67

#### <i><b><span style='color:#55679C'>Quest</span> : Buatkan report mengenai customer dan juga banyaknya transaksi pada data. Tampilkan customer_id dan jumlah_transaksi-nya sertakan total_komplain jika pelanggan tersebut pernah mengajukan komplain! Urutkan berdasarkan customer_id agar lebih mudah dibaca </b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

...

    customer_id  jumlah_transaksi  total_komplain
0    CUST001029                14               1
1    CUST001042               178              15
2    CUST001120                72               9
3    CUST001128               124              17
4    CUST001137               130              13
..          ...               ...             ...
115  CUST009458                19               3
116  CUST009708                36               3
117  CUST009740               523              45
118  CUST009755                98              11
119  CUST009993                88               7

[120 rows x 3 columns]

#### <i><b><span style='color:#55679C'>Quest</span> : Buatkan report mengenai jenis pizza dan hitung berapa kali pizza tersebut terjual dan hitung juga banyaknya (kuantitas) pizza tersebut pernah terjual! Urutkan berdasarkan kuantitas pizza terjual terbanyak!</b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

...

                pizza_id  pizza_terjual  total_kuantitas
0       PIZZA_BIG_MEAT_S           1811             1914
1       PIZZA_THAI_CKN_L           1365             1410
2    PIZZA_FIVE_CHEESE_L           1359             1409
3    PIZZA_FOUR_CHEESE_L           1273             1317
4    PIZZA_CLASSIC_DLX_M           1159             1181
..                   ...            ...              ...
86      PIZZA_MEXICANA_S            160              162
87     PIZZA_CALABRESE_S             99               99
88   PIZZA_CKN_ALFREDO_S             96               96
89  PIZZA_GREEN_GARDEN_L             94               95
90   PIZZA_THE_GREEK_XXL             28               28

[91 rows x 3 columns]

<a id="E"></a>
# <b>E. <span style='color:#0B2F9F'><code>HAVING</code></b>

HAVING dalam SQL digunakan untuk memfilter hasil dari kelompok data yang telah dikelompokkan dengan pernyataan GROUP BY. Mirip dengan klausa WHERE, tetapi HAVING bekerja setelah pengelompokan data dilakukan. Dengan kata lain, HAVING biasa digunakan untuk menerapkan kondisi pada hasil agregat.

<br>Gunakan fungsi having setelah pengelompokan dengan mengikuti sintaks <br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20Having.png" width="45%">

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan order_maker_id dan jumlah komplain yang pernah didapat. Filter hanya yang mendapat komplain lebih dari 210 kali, lalu urutkan dari yang paling banyak menerima komplain hingga paling sedikit </b></i><br>

In [ ]:
%%bigquery --project {project_id} --verbose

...

  order_maker_id  total_komplain
0      EMP000437             227
1      EMP000665             224
2      EMP000231             218
3      EMP000560             215
4      EMP000295             212
5      EMP000756             211

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---
<br>

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>